### ISSUE TITLE
Metis.partition return empty partition

### ISSUE THREAD

**Issue by ksun46** [JuliaSparse/Metis.jl#30]
I am using 
`Metis.partition(g, 7, alg = :KWAY)`
to partition a graph but the function returns
`Int32[2, 3, 5, 7, 2, 6, 6, 3, 1, 1, 1, 3, 1, 1, 7, 5, 5, 6, 5, 6, 5, 5, 7, 7, 7, 7, 2, 2, 3, 2, 2, 6, 6, 3, 3]`
It looks like 4 is missing and this partition has zero vertices. Could you please look into this? Thanks.

**Comment by jalving** [comment]
I have been using this Metis interface and have had this happen with some small graphs.  I think the direct k-way algorithm has this problem with very small partitions.  One option is to mess with the load imbalance parameter, but I don't think it is exposed through the Julia function.  Have you tried using
`alg = :RECURSIVE` to get non-empty partitions?

**Comment by ksun46** [comment]
I think this is because I was asking for too many partitions. The problem is gone when I use a more reasonable number for the graph, which is fine for my purpose. I haven't try the `algorithm = :RECURSIVE`, but I will take a look. Thanks

**Comment by ViralBShah** [comment]
Ok to close?

**Comment by kibaekkim** [comment]
I just had the same issue with `:KWAY`. Does `:RECURSIVE` guarantee to have non-empty partitions?

**Comment by jalving** [comment]
You can still get `:RECURSIVE` to return empty partitions if you give it a high enough (#partitions / #vertices) ratio. I don't know whether this happens in general with recursive bisection, or whether it is due to the multi-level partitioning strategy which METIS uses.   I think some algorithms can make guarantees if they can produce valid initial partitions.  For instance, https://github.com/kahypar/KaHyPar.jl isn't supposed to move a vertex to a new partition if it would cause the partition to become empty.  However, you can still get empty partitions at extreme (#partitions / #vertices) ratios likely due to initialization.

**Comment by kibaekkim** [comment]
I confirm that `:RECURSIVE` works quite well at least for my tests. Thanks @jalving! Good to see you here 😛

**Comment by jalving** [comment]
@kibaekkim It's a small computing world :grin: 

@ViralBShah This issue is over a year old.  I think it is alright to close.
