### ISSUE TITLE
Function to create a 0-based adjacency list from a SparseMatrixCSC object

### ISSUE THREAD

**Issue by dmbates** [JuliaSparse/Metis.jl#8]
The `SparseMatrixCSC` methods for `nodeND` and for `vertexSep` both create the adjacency list from the sparse matrix structure.  In the case of `vertexSep` it also converts to 0-based indices for use with ParMetis.  It would be better to isolate these operations in a separate function.

**Comment by dmbates** [comment]
I had the bright idea to implement this for graphs through `adjacency_matrix_sparse`.  That way everything would be routed through a method for sparse hermitian matrices and I would only need to do the 0-basing of the indices once.  Unfortunately, `adjacency_matrix_sparse` is very general and very slow.

**Comment by poulson** [comment]
How would this work with respect to returning a Julia data structure with zero indexing? I had looked into generalizing ``mkadj`` but stopped because I didn't know of the appropriate replacement for ``GeneralAdjacencyList``. A compromise might just be to create a routine which converts to/from 0-based and 1-based indexing for an adjacency list (and METIS has such a routine).

**Comment by dmbates** [comment]
I added 1 to the permutation, inverse permutation and the partitions produced by partGraphKway and PartGraphRecursive.
